runtime: nodejs20
 
env: standard
instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
- url: /static/css/(.*\.css)
  mime_type: text/css
  static_files: build/static/css/\1
  upload: build/static/css/(.*\.css)

- url: /static/js/(.*\.js)
  mime_type: text/javascript
  static_files: build/static/js/\1
  upload: build/static/js/(.*\.js)

- url: /static/media/(.*\.(png|jpg|jpeg|gif|bmp|svg|tiff|woff|woff2|eot|ttf|otf))
  static_files: build/static/media/\1
  upload: build/static/media/(.*\.(png|jpg|jpeg|gif|bmp|svg|tiff|woff|woff2|eot|ttf|otf))

- url: /(favicon\.ico|manifest\.json|logo192\.png|logo512\.png|asset-manifest\.json|robots\.txt)
  static_files: build/\1
  upload: build/(favicon\.ico|manifest\.json|logo192\.png|logo512\.png|asset-manifest\.json|robots\.txt)

- url: /.*
  static_files: build/index.html
  upload: build/index.html

env_variables:
  PORT: 8080