runtime: python311
entrypoint: gunicorn -b :$PORT -w 4 main:app -t 60
env: standard 
instance_class: F4 
service: backend


handlers:
- url: /.*  
  script: auto  


resources:
  cpu: 4
  memory_gb: 12
  disk_size_gb: 20 

# env_variables:
